version: "3.8"

services:
  plugin:
    image: node:lts-alpine
    working_dir: /app
    environment:
      TWILIO_AUTH_TOKEN: secret
      TWILIO_ACCOUNT_SID: ACxxx
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
